name: build-android-apk

on:
  workflow_dispatch:
  push:
    paths:
      - 'skyjo_kivy/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: skyjo_kivy   # folder with buildozer.spec + main.py
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          echo "Repo root:"
          ls -la ..
          echo
          echo "skyjo_kivy:"
          ls -la

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential \
              openjdk-17-jdk git unzip zlib1g-dev libffi-dev

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user Cython buildozer

      # Precreate license files so internal sdkmanager calls never prompt
      - name: Precreate Android SDK licenses (no prompts)
        run: |
          export ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/licenses"
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license"

      - name: Build APK (debug)
        env:
          PATH: ${{ env.HOME }}/.local/bin:${{ env.PATH }}
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skyjo-apk
          path: bin/*.apk
