name: build-android-apk

on:
  workflow_dispatch:
  push:
    paths:
      - 'skyjo_kivy/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev libunwind-dev zlib1g-dev \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev openssl libgdbm-dev \
            libgdbm-compat-dev liblzma-dev libreadline-dev uuid-dev \
            libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            zip unzip autoconf libtool pkg-config libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake libffi-dev libssl-dev automake

      - name: Set up Java 17 (for Gradle)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip dependencies (Buildozer & Cython)
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build with Buildozer (Android Debug)
        run: yes | buildozer -v android debug

      - name: Upload APK artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Skyjo-debug-apk
          path: bin/*.apk

      - name: Print build logs on failure
        if: ${{ failure() }}
        run: |
          echo "=== Showing last 50 lines of Buildozer logs ==="
          find .buildozer -type f \( -name "build*.log" -o -name "build*.txt" \) -print -exec tail -n 50 {} \;
