name: build-android-apk
on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '**.kv'
      - 'buildozer.spec'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential \
              openjdk-17-jdk git unzip zlib1g-dev libffi-dev

      - name: Install buildozer & p4a
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user Cython buildozer

      - name: Build APK (debug)
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skyjo-apk
          path: bin/*.apk
