name: build-android-apk

on:
  workflow_dispatch:
  push:
    paths:
      - 'skyjo_kivy/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: skyjo_kivy   # folder with buildozer.spec + main.py
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential \
              openjdk-17-jdk git unzip zlib1g-dev libffi-dev

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user buildozer Cython
          # <<< This line fixes "buildozer: command not found"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # (Optional) avoid SDK license prompts
      - name: Precreate Android SDK licenses
        run: |
          export ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/licenses"
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license"

      - name: Build APK (debug)
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skyjo-apk
          path: bin/*.apk
